Repository atc0005/go-teams-notify, pull requests merged in 2021-07, with the labels that each got.

#106 Update node-version val to use latest LTS version
  .github/workflows/lint-docs.yml
Labels: CI, config, dependencies, linting

#107 Replace golint, scopelint linters, cleanup cfg
  .golangci.yml
Labels: CI, config, linting

#103 Added structs to supports potential actions
  messagecard.go
Labels: enhancement

#108 Fix linting errors, adjust formatting
  messagecard.go
Labels: bug, documentation, linting

#109 Add `MessageCardSection.AddPotentialAction()` method
  messagecard.go
Labels: api, enhancement

#110 Extend MessageCardPotentialAction validation
  messagecard.go
Labels: api, enhancement

#112 Refresh docs to cover new PotentialActions support
  README.md
  doc.go
Labels: documentation

#114 Migrate examples from README to standalone files
  README.md
  examples/actions/main.go
  examples/basic/main.go
  examples/custom-validation/main.go
  examples/disable-validation/main.go
Labels: CI, builds, documentation, enhancement

#115 Refresh documentation for new release
  README.md
  doc.go
Labels: documentation

#116 Replace Markdown link refs with literal URL
  examples/actions/main.go
Labels: bug, documentation

#119 Update CHANGELOG for v2.6.0 release
  CHANGELOG.md
Labels: changelog
