Repository atc0005/go-teams-notify, pull requests merged in 2021-01, with the labels that each got.

#69 implemented hook to skip webhook URL validation
  send.go
Labels: enhancement

#70 Enable verbose test output by default
  .github/workflows/lint-and-test-only.yml
  Makefile
Labels: CI, logging, tests

#71 Fix breadcrumb URLs
  .gitignore
  .golangci.yml
  .markdownlint.yml
  doc.go
  go.mod
  messagecard.go
  send.go
  send_test.go
Labels: bug

#72 Replace godoc.org badge with pkg.go.dev badge
  README.md
Labels: documentation

#73 added missing API declaration
  send.go
Labels: bug

#74 Adjust receiver type to permit field changes
  send.go
Labels: api, bug

#76 tests: Update err type check, assert results
  send.go
  send_test.go
Labels: bug, tests

#77 Extend tests to cover optional URL validation
  send_test.go
Labels: enhancement, tests

#78 README: refresh current status, expand on history
  README.md
Labels: documentation

#79 README: Refresh examples, disable url prefix check
  README.md
Labels: api, documentation

#80 Update CHANGELOG for v2.4.0 release
  CHANGELOG.md
Labels: changelog

#81 Extend validation to assert specific response text
  send.go
  send_test.go
Labels: api, bug

#82 Update CHANGELOG for v2.4.1 release
  CHANGELOG.md
Labels: changelog

#85 SendWithRetry: Use receiver with existing settings
  send.go
Labels: api, bug

#86 Modify webhook URL prefix validation to use regex
  send.go
Labels: api, bug

#87 Clarify application of webhook URL validation
  README.md
  send.go
Labels: api, bug, config, documentation

#88 Update CHANGELOG for v2.4.2 release
  CHANGELOG.md
Labels: changelog
