Repository atc0005/go-teams-notify, pull requests merged in 2021-04, with the labels that each got.

#93 Better webhooks validation
  README.md
  messagecard.go
  send.go
  send_test.go
Labels: documentation, enhancement, tests

#97 Updates notes for recent examples
  README.md
Labels: bug, documentation

#98 Add section to list dependent projects
  README.md
Labels: documentation, enhancement

#99 Update features list
  README.md
Labels: documentation

#100 Update CHANGELOG for v2.5.0 release
  CHANGELOG.md
Labels: changelog
